Baby-Yoda-RN/food-hub

mobile/App.tsx
mobile/__mocks__/globalMock.js
mobile/package.json
mobile/storybook/addons.js
mobile/storybook/index.js
mobile/storybook/rn-addons.js
mobile/storybook/stories/Badge/Badge.stories.js
mobile/storybook/stories/Button/Button.stories.js
mobile/storybook/stories/Button/index.js
mobile/storybook/stories/CenterView/index.js
mobile/storybook/stories/CenterView/style.js
mobile/storybook/stories/Icon/Icon.stories.js
mobile/storybook/stories/Welcome/Welcome.stories.js
mobile/storybook/stories/Welcome/index.js
mobile/storybook/stories/index.js
mobile/yarn.lock

Init StoryBook

---

mobile/src/components/index.ts
mobile/src/components/sidemenu/SideMenu.styles.ts
mobile/src/components/sidemenu/SideMenu.tsx
mobile/src/components/sidemenu/SideMenu.type.ts

SideMenu rework

---

mobile/src/components/sidemenu/SideMenu.styles.ts
mobile/src/components/sidemenu/SideMenu.tsx

SideMenu: Update SideMenu after button change and font added

---

mobile/src/components/card/card.style.ts
mobile/src/components/card/card.tsx
mobile/src/components/card/card.type.ts
mobile/src/components/card/foodCard.tsx
mobile/src/components/card/restaurantCard.tsx

There was an issue that caused the card to not display any data. It has been fixed.

Card: Fixed render issue causing no information to appear

---

mobile/src/navigation/appNavigation/AppNavigation.tsx
mobile/src/navigation/appNavigation/AppNavigation.type.ts
mobile/src/navigation/index.ts
mobile/src/navigation/router/Router.tsx
mobile/src/screens/cart/Cart.tsx
mobile/src/screens/cart/Cart.type.ts
mobile/src/screens/cart/Cart.view.tsx
mobile/src/screens/index.ts
mobile/src/screens/login/Login.tsx
mobile/src/screens/review/Review.tsx
mobile/src/screens/review/Review.type.ts
mobile/src/screens/review/Review.view.tsx

AppNavigation: init

---

mobile/App.tsx
mobile/src/components/reviewCard/ReviewCard.style.ts
mobile/src/components/reviewCard/ReviewCard.tsx
mobile/src/components/reviewCard/ReviewCard.type.ts
mobile/src/types/data.ts

Created a component that will be used for the review screen.

Review Component

---

mobile/App.tsx
mobile/src/context/auth/auth.reducer.ts
mobile/src/context/auth/auth.state.ts
mobile/src/context/auth/auth.type.ts
mobile/src/context/auth/index.ts
mobile/src/context/global/global.context.ts
mobile/src/context/global/global.provider.tsx
mobile/src/context/global/global.reducer.ts
mobile/src/context/global/global.state.ts
mobile/src/context/global/global.type.ts
mobile/src/context/global/index.ts
mobile/src/context/user/user.reducer.ts
mobile/src/context/user/user.state.ts
mobile/src/context/user/user.type.ts
mobile/src/navigation/router/Router.tsx

src/context/user can be modified

Global Context init

---

mobile/src/components/sidemenu/SideMenu.tsx
mobile/src/components/textInput/TextInput.tsx
mobile/src/navigation/authNavigation/AuthNavigation.tsx
mobile/src/navigation/bottomTabNavigation/BottomTabNavigator.tsx
mobile/src/screens/resetPassword/ResetPassword.tsx

Note, we need extended paths for inputs to avoid the import cycle

Fixed Require Cycle, 

---

mobile/src/components/footer/Footer.style.ts
mobile/src/components/footer/Footer.tsx

fix Facebook and Google buttons

---

mobile/src/navigation/appNavigation/AppNavigation.type.ts
mobile/src/screens/home/Home.tsx
mobile/src/screens/home/Home.view.tsx
mobile/src/screens/rating/Rating.style.ts
mobile/src/screens/rating/Rating.tsx
mobile/src/screens/rating/Rating.type.ts
mobile/src/screens/rating/Rating.view.tsx
mobile/src/screens/review/Review.tsx
server/src/routes/home/home.data.ts
server/src/routes/restaurant/restaurant.type.ts

WIP:Review Screen: Fix

---

mobile/storybook/stories/header/Header.stories.js
mobile/storybook/stories/header/Header.style.js
mobile/storybook/stories/index.js

Dulaya/story book.header

---

mobile/storybook/stories/Icon/Icon.stories.js
mobile/storybook/stories/Icon/Icon.style.js

StoryBook: Icons

---

mobile/storybook/stories/index.js
mobile/storybook/stories/sideMenu/SideMenu.js
mobile/storybook/stories/sideMenu/SideMenu.style.js

Story Book: Side Menu

---

mobile/storybook/stories/Dropdown/Dropdown.stories.js
mobile/storybook/stories/Dropdown/Dropdown.style.js
mobile/storybook/stories/index.js
mobile/storybook/stories/orderCard/orderCard.stories.js

STORYBOOK: Order card

---

mobile/storybook/stories/index.js
mobile/storybook/stories/textInput/textInput.stories.js
mobile/storybook/stories/textInput/textInput.stories.view.js
mobile/storybook/stories/textInput/textInput.style.js

Storybook: textbox

---

mobile/storybook/stories/index.js
mobile/storybook/stories/toggleButton/ToggleButton.stories.js
mobile/storybook/stories/toggleButton/ToggleButton.style.js

Dulaya/story book.toggle button

---

mobile/storybook/stories/index.js
mobile/storybook/stories/tag/tag.stories.js
mobile/storybook/stories/tag/tag.style.js

STORYBOOK: Tag

---

mobile/storybook/stories/index.js
mobile/storybook/stories/ratingStars/RatingStars.stories.js

Story Book: Rating Stars

---

mobile/storybook/stories/Badge/Badge.stories.js
mobile/storybook/stories/Badge/Badge.style.js

Story Book: Badge

---

mobile/storybook/stories/bottomTabNavigator/BottomTabNavigator.stories.js
mobile/storybook/stories/bottomTabNavigator/BottomTabNavigator.style.js
mobile/storybook/stories/index.js

Story Book: Bottom Tab Navigator

---

mobile/src/screens/resetPassword/ResetPassword.tsx

Located the Recycle warning and fixed it. Please use the extended import for the navigation for the authNavigation

RecycleWarningFix:
